import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import { stripWatermark } from '@/lib/extract/watermark';
import { groupIntoLines } from '@/lib/extract/lines';
import type { PositionedItem } from '@/lib/types';

const pg1: PositionedItem[] = JSON.parse(fs.readFileSync('test/fixtures/pg1.items.json', 'utf8'));

describe('stripWatermark', () => {
  it('removes the 11x repeated department watermark', () => {
    const kept = stripWatermark(pg1);
    const still = kept.filter((i) => i.str.includes('fomd¾;fïka;=j'));
    expect(still).toHaveLength(0);
  });

  it('removes the repeated English watermark too', () => {
    const kept = stripWatermark(pg1);
    expect(kept.filter((i) => i.str.includes('Provincial Department'))).toHaveLength(0);
  });

  it('keeps option markers even though they repeat 7 times', () => {
    // Repetition alone must not be the rule — markers are legitimate content.
    const kept = stripWatermark(pg1);
    expect(kept.filter((i) => i.str.trim() === '^1&')).toHaveLength(7);
  });

  it('drops exactly the 22 watermark items (11 copies x 2 languages)', () => {
    // NOTE: deviates from the task-5 brief, which asserted
    // `toBeLessThan(pg1.length * 0.7)` under an assumption that watermark
    // items were ~48% of page 1. Measured against the real committed
    // fixture (test/fixtures/pg1.items.json, 128 items, generated by
    // test/tools/dump-fixtures.mjs from the actual PDF in fc1a961), the
    // watermark is exactly 22 items (11 Sinhala + 11 English) = ~17%, not
    // ~48%. The other three tests in this block already pin the precise,
    // confirmed behavior (0 Sinhala/English watermark items remain, all 7
    // option markers survive); this assertion is corrected to match that
    // same ground truth instead of the brief's inaccurate percentage.
    expect(pg1.length - stripWatermark(pg1).length).toBe(22);
  });
});

describe('groupIntoLines', () => {
  it('groups items sharing a y into one line', () => {
    const items: PositionedItem[] = [
      { str: 'b', x: 10, y: 100, w: 5, h: 10, font: 'FMAbhayax' },
      { str: ';', x: 16, y: 100, w: 5, h: 10, font: 'FMAbhayax' },
      { str: 'w', x: 10, y: 80, w: 5, h: 10, font: 'FMAbhayax' },
    ];
    const lines = groupIntoLines(items);
    expect(lines).toHaveLength(2);
    expect(lines[0].items).toHaveLength(2);
  });

  it('orders lines top to bottom and items left to right', () => {
    const items: PositionedItem[] = [
      { str: 'B', x: 50, y: 50, w: 5, h: 10, font: 'FMAbhayax' },
      { str: 'A', x: 10, y: 50, w: 5, h: 10, font: 'FMAbhayax' },
      { str: 'T', x: 10, y: 90, w: 5, h: 10, font: 'FMAbhayax' },
    ];
    const lines = groupIntoLines(items);
    expect(lines[0].items[0].str).toBe('T');
    expect(lines[1].items.map((i) => i.str)).toEqual(['A', 'B']);
  });

  it('transliterates line text to Unicode', () => {
    const items: PositionedItem[] = [
      { str: 'b;sydih', x: 10, y: 100, w: 40, h: 10, font: 'XSUOWA+FMAbhayax' },
    ];
    expect(groupIntoLines(items)[0].text).toBe('ඉතිහාසය');
  });

  it('carries the unmapped-glyph count forward instead of discarding it', () => {
    const items: PositionedItem[] = [
      { str: 'b;sydih', x: 10, y: 100, w: 40, h: 10, font: 'XSUOWA+FMAbhayax' },
    ];
    expect(groupIntoLines(items)[0].unmapped).toBe(0);
  });

  it('sums the unmapped count across every item on the line', () => {
    const items: PositionedItem[] = [
      { str: 'ZZ', x: 10, y: 100, w: 10, h: 10, font: 'XSUOWA+FMAbhayax' },
      { str: 'Z', x: 30, y: 100, w: 5, h: 10, font: 'XSUOWA+FMAbhayax' },
      { str: 'Z', x: 50, y: 100, w: 5, h: 10, font: 'BQCOZL+TimesNewRomanPSMT' },
    ];
    // Latin items are never converted, so only the three FM bytes count.
    expect(groupIntoLines(items)[0].unmapped).toBe(3);
  });
});
