import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import { stripWatermark } from '@/lib/extract/watermark';
import { groupIntoLines } from '@/lib/extract/lines';
import type { PositionedItem } from '@/lib/types';

const pg1: PositionedItem[] = JSON.parse(fs.readFileSync('test/fixtures/pg1.items.json', 'utf8'));

describe('stripWatermark', () => {
  it('removes the 11x repeated department watermark', () => {
    const kept = stripWatermark(pg1);
    const still = kept.filter((i) => i.str.includes('fomd¾;fïka;=j'));
    expect(still).toHaveLength(0);
  });

  it('removes the repeated English watermark too', () => {
    const kept = stripWatermark(pg1);
    expect(kept.filter((i) => i.str.includes('Provincial Department'))).toHaveLength(0);
  });

  it('keeps option markers even though they repeat 7 times', () => {
    // Repetition alone must not be the rule — markers are legitimate content.
    const kept = stripWatermark(pg1);
    expect(kept.filter((i) => i.str.trim() === '^1&')).toHaveLength(7);
  });

  it('drops exactly the 22 watermark items (11 copies x 2 languages)', () => {
    // NOTE: deviates from the task-5 brief, which asserted
    // `toBeLessThan(pg1.length * 0.7)` under an assumption that watermark
    // items were ~48% of page 1. Measured against the real committed
    // fixture (test/fixtures/pg1.items.json, 128 items, generated by
    // test/tools/dump-fixtures.mjs from the actual PDF in fc1a961), the
    // watermark is exactly 22 items (11 Sinhala + 11 English) = ~17%, not
    // ~48%. The other three tests in this block already pin the precise,
    // confirmed behavior (0 Sinhala/English watermark items remain, all 7
    // option markers survive); this assertion is corrected to match that
    // same ground truth instead of the brief's inaccurate percentage.
    expect(pg1.length - stripWatermark(pg1).length).toBe(22);
  });
});

describe('groupIntoLines', () => {
  it('groups items sharing a y into one line', () => {
    const items: PositionedItem[] = [
      { str: 'b', x: 10, y: 100, w: 5, h: 10, font: 'FMAbhayax' },
      { str: ';', x: 16, y: 100, w: 5, h: 10, font: 'FMAbhayax' },
      { str: 'w', x: 10, y: 80, w: 5, h: 10, font: 'FMAbhayax' },
    ];
    const lines = groupIntoLines(items);
    expect(lines).toHaveLength(2);
    expect(lines[0].items).toHaveLength(2);
  });

  it('orders lines top to bottom and items left to right', () => {
    const items: PositionedItem[] = [
      { str: 'B', x: 50, y: 50, w: 5, h: 10, font: 'FMAbhayax' },
      { str: 'A', x: 10, y: 50, w: 5, h: 10, font: 'FMAbhayax' },
      { str: 'T', x: 10, y: 90, w: 5, h: 10, font: 'FMAbhayax' },
    ];
    const lines = groupIntoLines(items);
    expect(lines[0].items[0].str).toBe('T');
    expect(lines[1].items.map((i) => i.str)).toEqual(['A', 'B']);
  });

  it('transliterates line text to Unicode', () => {
    const items: PositionedItem[] = [
      { str: 'b;sydih', x: 10, y: 100, w: 40, h: 10, font: 'XSUOWA+FMAbhayax' },
    ];
    expect(groupIntoLines(items)[0].text).toBe('ඉතිහාසය');
  });

  it('carries the unmapped-glyph count forward instead of discarding it', () => {
    const items: PositionedItem[] = [
      { str: 'b;sydih', x: 10, y: 100, w: 40, h: 10, font: 'XSUOWA+FMAbhayax' },
    ];
    expect(groupIntoLines(items)[0].unmapped).toBe(0);
  });

  it('sums the unmapped count across every item on the line', () => {
    // '\x01' stands in for "any byte with no token" (see the same swap in
    // test/sinhala/convert.test.ts — 'Z' used to fill this role until it was
    // confirmed to be a real closing-quote token).
    const items: PositionedItem[] = [
      { str: '\x01\x01', x: 10, y: 100, w: 10, h: 10, font: 'XSUOWA+FMAbhayax' },
      { str: '\x01', x: 30, y: 100, w: 5, h: 10, font: 'XSUOWA+FMAbhayax' },
      { str: '\x01', x: 50, y: 100, w: 5, h: 10, font: 'BQCOZL+TimesNewRomanPSMT' },
    ];
    // Latin items are never converted, so only the three FM bytes count.
    expect(groupIntoLines(items)[0].unmapped).toBe(3);
  });

  /**
   * Real user report: pdf.js splits one visual line into several items
   * wherever the PDF restarts a text-showing operator — here, a bold-styled
   * mid-sentence word ("lr weÍu", font FMAbabldBold) breaks the sentence
   * into three items. The real x/y/w values below are read straight from
   * the reported PDF's own page 1. Naively concatenating item text glued
   * "...ඇරීම" onto "දිනිඳුගේ..." with no space, producing
   * "ඇරීමදිනිඳුගේ" — a single, wrong, run-together word.
   */
  it('inserts a space between items that pdf.js split at a font/style change', () => {
    const items: PositionedItem[] = [
      { str: "YsIH kdhlhska mjrk jevj, §", x: 84.97, y: 508.91, w: 149.7, h: 12, font: 'WBQLYM+FMAbhayax' },
      { str: 'lr weÍu', x: 237.33, y: 508.91, w: 42.79, h: 12, font: 'UHDOMO+FMAbabldBold' },
      { str: "Èks`ÿf.a isß; h'", x: 282.78, y: 508.91, w: 75.41, h: 12, font: 'WBQLYM+FMAbhayax' },
    ];
    expect(groupIntoLines(items)[0].text).toBe('ශිෂ්‍ය නායකයින් පවරන වැඩවල දී කර ඇරීම දිනිඳුගේ සිරිත ය.');
  });

  /**
   * The one case where two items must stay glued with NO inserted space:
   * a question-number opener ("01") and the stem's first word are separate
   * items with no space in the source PDF (only visual padding) — see the
   * lib/extract/lines.ts joinItemTexts doc comment. parser.ts's
   * QUESTION_START relies on this staying glued to tell a real opener apart
   * from a bare header number with a genuine embedded space (e.g. a single
   * item "11 fY%aKsh" -> "11 ශ්‍රේණිය", never split like this).
   */
  it('does not insert a space between a bare question-number opener and the stem', () => {
    const items: PositionedItem[] = [
      { str: '01', x: 56.69, y: 508.91, w: 9.91, h: 12, font: 'WBQLYM+FMAbhayax' },
      { str: "YsIH kdhlhska", x: 84.97, y: 508.91, w: 149.7, h: 12, font: 'WBQLYM+FMAbhayax' },
    ];
    expect(groupIntoLines(items)[0].text.startsWith('01ශිෂ්‍ය')).toBe(true);
  });
});
