import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import type { BBox } from '@/lib/types';

// Keyed by 0-based pageIndex. Generated by test/tools/dump-fixtures.mjs,
// which duplicates lib/pdf/images.ts#getImageRegions's operator-list walk
// (same reason the text-item fixtures duplicate lib/pdf/textLayer.ts: the
// dumper runs under plain Node against the legacy pdf.js build, and pure
// vitest tests must never need to import pdf.js themselves).
const imageRegionsByPage: Record<string, BBox[]> = JSON.parse(
  fs.readFileSync('test/fixtures/image-regions.json', 'utf8'),
);

describe('embedded image regions (real reference PDF)', () => {
  it('page index 0 has exactly 1 drawn image', () => {
    expect(imageRegionsByPage['0']).toHaveLength(1);
  });

  // NOTE on a deviation from the task-4 ruling's stated fact-check:
  //
  // The ruling states "page index 4 (page 5) has 3, page index 5 (page 6)
  // has 2" embedded images. That count was derived (verified independently
  // with pdf-lib against this same fixture) from the number of distinct
  // `/XObject` `/Image` entries declared in each page's `/Resources`
  // dictionary: page index 4 declares 3 (`Im434`, `Im435`, `Im436`), page
  // index 5 declares 2 (`Im442`, `Im443`).
  //
  // But per-page, one of those declared XObjects on each page is an
  // `/SMask` (soft mask) attached to the *other* image on the same page
  // (Im435 is Im436's SMask; Im442 is Im443's SMask) — confirmed by
  // inspecting each XObject's dict. pdf.js resolves an image's SMask
  // internally while decoding the base image (folding it into the
  // decoded bitmap's alpha channel) and never emits a separate
  // `paintImageXObject` / `paintImageMaskXObject` operator for it. An
  // SMask has no bounding box of its own distinct from the image it
  // belongs to — it modulates that image's alpha at that same location —
  // so getImageRegions, which walks *draw operations* per the ruling's own
  // implementation instructions (read the operator list for
  // paintImageXObject/paintImageMaskXObject and convert the active
  // transform), correctly reports 2 and 1 drawn images on these pages, not
  // 3 and 2. Counting declared resources instead would double-report the
  // same visible region for any masked image.
  it('page index 4 has 2 drawn images (3 declared XObjects; 1 is an SMask of another)', () => {
    expect(imageRegionsByPage['4']).toHaveLength(2);
  });

  it('page index 5 has 1 drawn image (2 declared XObjects; 1 is an SMask of the other)', () => {
    expect(imageRegionsByPage['5']).toHaveLength(1);
  });

  it('every region has finite, positive-area bounds', () => {
    for (const regions of Object.values(imageRegionsByPage)) {
      for (const bbox of regions) {
        expect(Number.isFinite(bbox.x)).toBe(true);
        expect(Number.isFinite(bbox.y)).toBe(true);
        expect(bbox.w).toBeGreaterThan(0);
        expect(bbox.h).toBeGreaterThan(0);
      }
    }
  });
});
